const {
  USR,
  PWD_REQ,
  PRDT,
  CRT_ROW,
  ADDRESS,
  BILL,
  BILLPRDT,
  DELIVERY,
  BACKUP,
  HISTORY
} = require('./strings');

const TABLES = [USR, PWD_REQ, PRDT, CRT_ROW, ADDRESS, BILL, BILLPRDT, DELIVERY, BACKUP, HISTORY];

module.exports = TABLES;
