const {
  USR,
  PWD_REQ,
  GNDR,
  BRND,
  CTGR,
  PRDT,
  IMG,
  DISC,
  CRT_ROW,
  ADDRESS,
  BILL,
  BILLPRDT,
  DELIVERY,
  BACKUP
} = require('./strings');

const TABLES = [USR, PWD_REQ, GNDR, BRND, CTGR, PRDT, IMG, DISC, CRT_ROW, ADDRESS, BILL, BILLPRDT, DELIVERY, BACKUP];

module.exports = TABLES;
