apiVersion: v1
kind: Service
metadata:
  name: monolith
  labels:
    name: monolith
    app: fastcommerce
spec:
  selector:
    name: monolith
  type: NodePort
  ports:
    - name: monolith
      port: 6000
      targetPort: 6000
      nodePort: 36000
      protocol: TCP