apiVersion: v1
kind: Service
metadata:
  name: monolith-db
  labels:
    name: monolith-db
    app: fastcommerce
spec:
  selector:
    name: monolith-db
  type: ClusterIP
  ports:
    - name: monolith-db
      port: 5432
      targetPort: 5432
