apiVersion: v1
kind: Pod
metadata:
  name: monolith-db
  labels:
    name: monolith-db
    app: fastcommerce
spec:
  containers:
    - image: postgres
      name: postgres
      env:
        - name: POSTGRES_PASSWORD
          value: root
      ports:
        - name: postgres
          containerPort: 5432
