apiVersion: v1
kind: Service
metadata:
  name: backup
  labels:
    name: backup
    app: fastcommerce
spec:
  selector:
    name: backup
  type: NodePort
  ports:
    - name: backup
      port: 5013
      targetPort: 5013
      nodePort: 30013
      protocol: TCP