apiVersion: v1
kind: Pod
metadata:
  name: backup
  labels:
    name: backup
    app: fastcommerce
spec:
  containers:
    - image: hkhattabi/backup-svc
      name: backup
      ports:
        - name: backup
          containerPort: 5013
