apiVersion: v1
kind: Pod
metadata:
  name: product-db
  labels:
    name: product-db
    app: fastcommerce
spec:
  containers:
    - image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
      name: elasticsearch
      env:
        - name: discovery.type
          value: single-node
      ports:
        - name: elasticsearch
          containerPort: 9200
