apiVersion: v1
kind: Service
metadata:
  name: product
  labels:
    name: product
    app: fastcommerce
spec:
  selector:
    name: product
  type: NodePort
  ports:
    - name: product
      port: 5002
      targetPort: 5002
      nodePort: 30002
      protocol: TCP