apiVersion: v1
kind: Pod
metadata:
  name: product
  labels:
    name: product
    app: fastcommerce
spec:
  containers:
    - image: hkhattabi/product-svc
      name: product
      ports:
        - name: product
          containerPort: 5002
