apiVersion: v1
kind: Pod
metadata:
  name: discount-code-db
  labels:
    name: discount-code-db
    app: fastcommerce
spec:
  containers:
    - image: postgres
      name: postgres
      env:
        - name: POSTGRES_PASSWORD
          value: root
      volumeMounts:
        - name: init-db
          mountPath: /docker-entrypoint.initdb.d
      ports:
        - name: postgres
          containerPort: 5432
  volumes:
    - name: init-db
      configMap:
        name: init.sql
