apiVersion: v1
kind: Pod
metadata:
  name: discount-code
  labels:
    name: discount-code
    app: fastcommerce
spec:
  containers:
    - image: hkhattabi/discount-code-svc
      name: discount-code
      ports:
        - name: discount-code
          containerPort: 5009
