apiVersion: v1
kind: Pod
metadata:
  name: discount-code-db
  labels:
    name: discount-code-db
    app: fastcommerce
spec:
  containers:
    - image: mongo
      name: mongo
      ports:
        - name: mongo
          containerPort: 27017
