apiVersion: v1
kind: Service
metadata:
  name: bill
  labels:
    name: bill
    app: fastcommerce
spec:
  selector:
    name: bill
  type: NodePort
  ports:
    - name: bill
      port: 5011
      targetPort: 5011
      nodePort: 30004
      protocol: TCP