apiVersion: v1
kind: Service
metadata:
  name: bill-db
  labels:
    name: bill-db
    app: fastcommerce
spec:
  selector:
    name: bill-db
  type: ClusterIP
  ports:
    - name: bill-db
      port: 27017
      targetPort: 27017