apiVersion: v1
kind: Service
metadata:
  name: auth
  labels:
    name: auth
    app: fastcommerce
spec:
  selector:
    name: auth
  type: NodePort
  ports:
    - name: auth
      port: 5001
      targetPort: 5001
      nodePort: 30001
      protocol: TCP