apiVersion: v1
kind: Service
metadata:
  name: delivery
  labels:
    name: delivery
    app: fastcommerce
spec:
  selector:
    name: delivery
  type: NodePort
  ports:
    - name: delivery
      port: 5015
      targetPort: 5015
      nodePort: 30015
      protocol: TCP