services:
    password-request:
        build: ./password-request-service
        ports:
            - '5003:5003'
        links:
            - password-request-db
    password-request-db:
        image: postgres
        restart: always
        environment: 
            - POSTGRES_HOST_AUTH_METHOD=trust
        volumes:
            - ./init:/docker-entrypoint-initdb.d
        ports:
            - '5004:5432'