apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNVEEwTVRZdwpPVFExTlRGYUZ3MDBNVEEwTVRZd09UUTFOVEZhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFES0tqUkxJZmYxMFo4WGFyQzE3OVJWcFRhblVtSFVQRjBZQ1B3VHlPN1lpMHhtMnkvcgpiYm1IODhyVXpsbXQrTDVTMUFpcjVLRE1xMTVSUFlTczR4R3J1TEcyZjhBR3RjRHZ2OTB5TTFRWjloSEU1b2NTCkVRbHltV3NwcWlZUi8zaTVreWJEMFp6WWZBMy9DejROKzU0M2V0Mms1Y1B5TDJQd21KVjFsQ0hQTmc4MmsvZnoKWElKL1BqdTkzVWpBTVZEYU82cHN1Rlk1U1NYQ1BPcHVwV1RTWVE1MzcrMjF3R3YrbmppaTFGeUw3RHlzeTBQaAphYVUrVFoyNi9OSUJiOGdUdkN5WkthSDhQWFU0K2ZoY01EdGRyWDdCWGhtZEc4UnpuVGpFWlZRUFFha05PcnJlClF4NzZMMHBHUjhsMi9XK2ZCRjhkRzdHL21iZkhpcFlVMDI0WEFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlNNOW5iN1lFM1ZFSmhRS2VxRQp4Umo4aGJVWTREQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFDSlRkODJoalJ3OG5lOEZlMUFFZjlNTkJkZnBSCml1clZyTElKdjVZWTFERmhpc0hSeFhIRHRYNkdOMEtjQ3MyenVyb0xqbXJsYTVtcDlwVHZFZnNWREx5OGVXSysKVGM2TFZ1SHdzZUZCMkFrWlVnS1NCQ1FkNTVvSW9xOCsybTh2Ulc3cmo2Qkg5WDdkOHQ0VVgxRmR6M3N6NVlrRgpHOXQvNDlaNHBCM21tYzhlVU93ZEVudzhtckVHOU5WcnRXMjNnaXNXQzBpYUZRbVBQeUJId0RlMDg5WjBtRDBaCnZ6ZXhtNFBQUzdGU0VralFDbWY1YjE3NjlJY2FKT083UHhOdDBLT0ZSa1hVbTZpUi92NDlUenhxWVcyZEdqaHEKcmZIaXNHeU9Ta1F4bjBYOVRPd2Y3bTJITkN1blF5bG80clM5ek1INFRtb2F4TnIvQmU0dEZMZHB3QT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://f77685ee-31a0-40ff-9683-11cb620294cc.k8s.ondigitalocean.com
  name: do-ams3-fastcommerce-cluster
contexts:
- context:
    cluster: do-ams3-fastcommerce-cluster
    user: do-ams3-fastcommerce-cluster-admin
  name: do-ams3-fastcommerce-cluster
current-context: do-ams3-fastcommerce-cluster
kind: Config
preferences: {}
users:
- name: do-ams3-fastcommerce-cluster-admin
  user:
    token: acc43eb80b81e1e08602f07dbcbfb531f1213a57375a1fe93af7027656662159
