apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    name: gateway
    app: fastcommerce
spec:
  selector:
    name: gateway
  type: NodePort
  ports:
    - name: gateway
      port: 3000
      targetPort: 3000
      nodePort: 30000
      protocol: TCP