apiVersion: v1
kind: Pod
metadata:
  name: gateway
  labels:
    name: gateway
    app: fastcommerce
spec:
  containers:
    - image: hkhattabi/gateway
      name: gateway
      ports:
        - name: gateway
          containerPort: 3000







