apiVersion: v1
kind: Pod
metadata:
  name: password-request
  labels:
    name: password-request
    app: fastcommerce
spec:
  containers:
    - image: hkhattabi/password-request-svc
      name: password-request
      ports:
        - name: password-request
          containerPort: 5009
