apiVersion: v1
kind: Service
metadata:
  name: password-request-db
  labels:
    name: password-request-db
    app: fastcommerce
spec:
  selector:
    name: password-request-db
  type: ClusterIP
  ports:
    - name: password-request-db
      port: 5432
      targetPort: 5432
