apiVersion: v1
kind: Service
metadata:
  name: password-request
  labels:
    name: password-request
    app: fastcommerce
spec:
  selector:
    name: password-request
  type: NodePort
  ports:
    - name: password-request
      port: 5009
      targetPort: 5009
      nodePort: 30007
      protocol: TCP